from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, Self, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.engine_param_binding_payload_v2 import EngineParamBindingPayloadV2


T = TypeVar("T", bound="AlertRouteAutoGeneratedTemplateBindingPayloadV2")


@_attrs_define(kw_only=True)
class AlertRouteAutoGeneratedTemplateBindingPayloadV2:
    """
    Example:
        {'autogenerated': False, 'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}],
            'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}

    Attributes:
        autogenerated (bool | Unset): Whether this attribute is autogenerated using AI or not Example: False.
        binding (EngineParamBindingPayloadV2 | Unset):  Example: {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}.
    """

    autogenerated: bool | Unset = UNSET
    binding: EngineParamBindingPayloadV2 | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        autogenerated = self.autogenerated

        binding: dict[str, Any] | Unset = UNSET
        if not isinstance(self.binding, Unset):
            binding = self.binding.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if autogenerated is not UNSET:
            field_dict["autogenerated"] = autogenerated
        if binding is not UNSET:
            field_dict["binding"] = binding

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        from ..models.engine_param_binding_payload_v2 import (
            EngineParamBindingPayloadV2,
        )

        d = dict(src_dict)
        autogenerated = d.pop("autogenerated", UNSET)

        _binding = d.pop("binding", UNSET)
        binding: EngineParamBindingPayloadV2 | Unset
        if isinstance(_binding, Unset):
            binding = UNSET
        else:
            binding = EngineParamBindingPayloadV2.from_dict(_binding)

        alert_route_auto_generated_template_binding_payload_v2 = cls(
            autogenerated=autogenerated,
            binding=binding,
        )

        alert_route_auto_generated_template_binding_payload_v2.additional_properties = d
        return alert_route_auto_generated_template_binding_payload_v2

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
