from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, Self, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.alert_route_auto_generated_template_binding_v3 import (
        AlertRouteAutoGeneratedTemplateBindingV3,
    )
    from ..models.alert_route_custom_field_binding_v3 import (
        AlertRouteCustomFieldBindingV3,
    )
    from ..models.alert_route_severity_binding_v3 import AlertRouteSeverityBindingV3
    from ..models.alert_route_template_binding_v3 import AlertRouteTemplateBindingV3


T = TypeVar("T", bound="AlertRouteIncidentTemplateV3")


@_attrs_define(kw_only=True)
class AlertRouteIncidentTemplateV3:
    """The template an alert route applies to the incidents it creates. Disabling incident creation clears it.

    Example:
        {'custom_fields': [{'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}],
            'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}, 'custom_field_id':
            '01FCNDV6P870EA6S7TK1DSYDG0', 'merge_strategy': 'first-wins'}], 'incident_mode': {'binding': {'array_value':
            [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}, 'incident_type': {'binding': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}, 'membership_teams':
            {'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal':
            'SEV123', 'reference': 'incident.severity'}}}, 'name': {'autogenerated': False, 'binding': {'array_value':
            [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}, 'severity': {'binding': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}, 'merge_strategy':
            'first-wins'}, 'start_in_triage': {'binding': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}, 'summary':
            {'autogenerated': False, 'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}],
            'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}}

    Attributes:
        name (AlertRouteAutoGeneratedTemplateBindingV3):  Example: {'autogenerated': False, 'binding': {'array_value':
            [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}.
        custom_fields (list[AlertRouteCustomFieldBindingV3] | Unset): Custom fields configuration Example: [{'binding':
            {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123',
            'reference': 'incident.severity'}}, 'custom_field_id': '01FCNDV6P870EA6S7TK1DSYDG0', 'merge_strategy': 'first-
            wins'}].
        incident_mode (AlertRouteTemplateBindingV3 | Unset):  Example: {'binding': {'array_value': [{'literal':
            'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}.
        incident_type (AlertRouteTemplateBindingV3 | Unset):  Example: {'binding': {'array_value': [{'literal':
            'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}.
        membership_teams (AlertRouteTemplateBindingV3 | Unset):  Example: {'binding': {'array_value': [{'literal':
            'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}.
        severity (AlertRouteSeverityBindingV3 | Unset):  Example: {'binding': {'array_value': [{'literal': 'SEV123',
            'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}},
            'merge_strategy': 'first-wins'}.
        start_in_triage (AlertRouteTemplateBindingV3 | Unset):  Example: {'binding': {'array_value': [{'literal':
            'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}.
        summary (AlertRouteAutoGeneratedTemplateBindingV3 | Unset):  Example: {'autogenerated': False, 'binding':
            {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123',
            'reference': 'incident.severity'}}}.
    """

    name: AlertRouteAutoGeneratedTemplateBindingV3
    custom_fields: list[AlertRouteCustomFieldBindingV3] | Unset = UNSET
    incident_mode: AlertRouteTemplateBindingV3 | Unset = UNSET
    incident_type: AlertRouteTemplateBindingV3 | Unset = UNSET
    membership_teams: AlertRouteTemplateBindingV3 | Unset = UNSET
    severity: AlertRouteSeverityBindingV3 | Unset = UNSET
    start_in_triage: AlertRouteTemplateBindingV3 | Unset = UNSET
    summary: AlertRouteAutoGeneratedTemplateBindingV3 | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name.to_dict()

        custom_fields: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.custom_fields, Unset):
            custom_fields = []
            for custom_fields_item_data in self.custom_fields:
                custom_fields_item = custom_fields_item_data.to_dict()
                custom_fields.append(custom_fields_item)

        incident_mode: dict[str, Any] | Unset = UNSET
        if not isinstance(self.incident_mode, Unset):
            incident_mode = self.incident_mode.to_dict()

        incident_type: dict[str, Any] | Unset = UNSET
        if not isinstance(self.incident_type, Unset):
            incident_type = self.incident_type.to_dict()

        membership_teams: dict[str, Any] | Unset = UNSET
        if not isinstance(self.membership_teams, Unset):
            membership_teams = self.membership_teams.to_dict()

        severity: dict[str, Any] | Unset = UNSET
        if not isinstance(self.severity, Unset):
            severity = self.severity.to_dict()

        start_in_triage: dict[str, Any] | Unset = UNSET
        if not isinstance(self.start_in_triage, Unset):
            start_in_triage = self.start_in_triage.to_dict()

        summary: dict[str, Any] | Unset = UNSET
        if not isinstance(self.summary, Unset):
            summary = self.summary.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "name": name,
            }
        )
        if custom_fields is not UNSET:
            field_dict["custom_fields"] = custom_fields
        if incident_mode is not UNSET:
            field_dict["incident_mode"] = incident_mode
        if incident_type is not UNSET:
            field_dict["incident_type"] = incident_type
        if membership_teams is not UNSET:
            field_dict["membership_teams"] = membership_teams
        if severity is not UNSET:
            field_dict["severity"] = severity
        if start_in_triage is not UNSET:
            field_dict["start_in_triage"] = start_in_triage
        if summary is not UNSET:
            field_dict["summary"] = summary

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        from ..models.alert_route_auto_generated_template_binding_v3 import (
            AlertRouteAutoGeneratedTemplateBindingV3,
        )
        from ..models.alert_route_custom_field_binding_v3 import (
            AlertRouteCustomFieldBindingV3,
        )
        from ..models.alert_route_severity_binding_v3 import (
            AlertRouteSeverityBindingV3,
        )
        from ..models.alert_route_template_binding_v3 import (
            AlertRouteTemplateBindingV3,
        )

        d = dict(src_dict)
        name = AlertRouteAutoGeneratedTemplateBindingV3.from_dict(d.pop("name"))

        _custom_fields = d.pop("custom_fields", UNSET)
        custom_fields: list[AlertRouteCustomFieldBindingV3] | Unset = UNSET
        if _custom_fields is not UNSET:
            custom_fields = []
            for custom_fields_item_data in _custom_fields:
                custom_fields_item = AlertRouteCustomFieldBindingV3.from_dict(
                    custom_fields_item_data
                )

                custom_fields.append(custom_fields_item)

        _incident_mode = d.pop("incident_mode", UNSET)
        incident_mode: AlertRouteTemplateBindingV3 | Unset
        if isinstance(_incident_mode, Unset):
            incident_mode = UNSET
        else:
            incident_mode = AlertRouteTemplateBindingV3.from_dict(_incident_mode)

        _incident_type = d.pop("incident_type", UNSET)
        incident_type: AlertRouteTemplateBindingV3 | Unset
        if isinstance(_incident_type, Unset):
            incident_type = UNSET
        else:
            incident_type = AlertRouteTemplateBindingV3.from_dict(_incident_type)

        _membership_teams = d.pop("membership_teams", UNSET)
        membership_teams: AlertRouteTemplateBindingV3 | Unset
        if isinstance(_membership_teams, Unset):
            membership_teams = UNSET
        else:
            membership_teams = AlertRouteTemplateBindingV3.from_dict(_membership_teams)

        _severity = d.pop("severity", UNSET)
        severity: AlertRouteSeverityBindingV3 | Unset
        if isinstance(_severity, Unset):
            severity = UNSET
        else:
            severity = AlertRouteSeverityBindingV3.from_dict(_severity)

        _start_in_triage = d.pop("start_in_triage", UNSET)
        start_in_triage: AlertRouteTemplateBindingV3 | Unset
        if isinstance(_start_in_triage, Unset):
            start_in_triage = UNSET
        else:
            start_in_triage = AlertRouteTemplateBindingV3.from_dict(_start_in_triage)

        _summary = d.pop("summary", UNSET)
        summary: AlertRouteAutoGeneratedTemplateBindingV3 | Unset
        if isinstance(_summary, Unset):
            summary = UNSET
        else:
            summary = AlertRouteAutoGeneratedTemplateBindingV3.from_dict(_summary)

        alert_route_incident_template_v3 = cls(
            name=name,
            custom_fields=custom_fields,
            incident_mode=incident_mode,
            incident_type=incident_type,
            membership_teams=membership_teams,
            severity=severity,
            start_in_triage=start_in_triage,
            summary=summary,
        )

        alert_route_incident_template_v3.additional_properties = d
        return alert_route_incident_template_v3

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
