from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, Self, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.alert_route_incident_template_payload_v3 import (
        AlertRouteIncidentTemplatePayloadV3,
    )
    from ..models.condition_group_payload_v3 import ConditionGroupPayloadV3
    from ..models.engine_param_binding_payload_v3 import EngineParamBindingPayloadV3


T = TypeVar("T", bound="AlertRouteIncidentConfigPayloadV3")


@_attrs_define(kw_only=True)
class AlertRouteIncidentConfigPayloadV3:
    """
    Example:
        {'auto_decline_enabled': False, 'condition_groups': [{'conditions': [{'operation': 'one_of', 'param_bindings':
            [{'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123',
            'reference': 'incident.severity'}}], 'subject': 'alert.priority'}]}], 'enabled': False, 'incident_template':
            {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123',
            'reference': 'incident.severity'}}, 'membership_teams': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}, 'template':
            {'custom_fields': [{'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}],
            'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}, 'custom_field_id':
            '01FCNDV6P870EA6S7TK1DSYDG0', 'merge_strategy': 'first-wins'}], 'incident_mode': {'binding': {'array_value':
            [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}, 'incident_type': {'binding': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}, 'membership_teams':
            {'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal':
            'SEV123', 'reference': 'incident.severity'}}}, 'name': {'autogenerated': False, 'binding': {'array_value':
            [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference':
            'incident.severity'}}}, 'severity': {'binding': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}, 'merge_strategy':
            'first-wins'}, 'start_in_triage': {'binding': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}, 'summary':
            {'autogenerated': False, 'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}],
            'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}}}

    Attributes:
        enabled (bool): Whether incident creation is enabled for this alert route Example: False.
        auto_decline_enabled (bool | Unset): Should triage incidents be declined when alerts are resolved? Required when
            incident creation is enabled, and must be unset otherwise. Example: False.
        condition_groups (list[ConditionGroupPayloadV3] | Unset): What condition groups must be true for this alert
            route to create an incident? Only set when incident creation is enabled. Example: [{'conditions': [{'operation':
            'one_of', 'param_bindings': [{'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value':
            {'literal': 'SEV123', 'reference': 'incident.severity'}}], 'subject': 'alert.priority'}]}].
        incident_template (EngineParamBindingPayloadV3 | Unset):  Example: {'array_value': [{'literal': 'SEV123',
            'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}.
        membership_teams (EngineParamBindingPayloadV3 | Unset):  Example: {'array_value': [{'literal': 'SEV123',
            'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}.
        template (AlertRouteIncidentTemplatePayloadV3 | Unset): The template this alert route applies to the incidents
            it creates. It must be unset when incident creation is disabled. Disabling incident creation clears a template
            the route already has. Example: {'custom_fields': [{'binding': {'array_value': [{'literal': 'SEV123',
            'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}},
            'custom_field_id': '01FCNDV6P870EA6S7TK1DSYDG0', 'merge_strategy': 'first-wins'}], 'incident_mode': {'binding':
            {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123',
            'reference': 'incident.severity'}}}, 'incident_type': {'binding': {'array_value': [{'literal': 'SEV123',
            'reference': 'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}},
            'membership_teams': {'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}],
            'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}, 'name': {'autogenerated': False, 'binding':
            {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}], 'value': {'literal': 'SEV123',
            'reference': 'incident.severity'}}}, 'severity': {'binding': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}, 'merge_strategy':
            'first-wins'}, 'start_in_triage': {'binding': {'array_value': [{'literal': 'SEV123', 'reference':
            'incident.severity'}], 'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}, 'summary':
            {'autogenerated': False, 'binding': {'array_value': [{'literal': 'SEV123', 'reference': 'incident.severity'}],
            'value': {'literal': 'SEV123', 'reference': 'incident.severity'}}}}.
    """

    enabled: bool
    auto_decline_enabled: bool | Unset = UNSET
    condition_groups: list[ConditionGroupPayloadV3] | Unset = UNSET
    incident_template: EngineParamBindingPayloadV3 | Unset = UNSET
    membership_teams: EngineParamBindingPayloadV3 | Unset = UNSET
    template: AlertRouteIncidentTemplatePayloadV3 | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        enabled = self.enabled

        auto_decline_enabled = self.auto_decline_enabled

        condition_groups: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.condition_groups, Unset):
            condition_groups = []
            for condition_groups_item_data in self.condition_groups:
                condition_groups_item = condition_groups_item_data.to_dict()
                condition_groups.append(condition_groups_item)

        incident_template: dict[str, Any] | Unset = UNSET
        if not isinstance(self.incident_template, Unset):
            incident_template = self.incident_template.to_dict()

        membership_teams: dict[str, Any] | Unset = UNSET
        if not isinstance(self.membership_teams, Unset):
            membership_teams = self.membership_teams.to_dict()

        template: dict[str, Any] | Unset = UNSET
        if not isinstance(self.template, Unset):
            template = self.template.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "enabled": enabled,
            }
        )
        if auto_decline_enabled is not UNSET:
            field_dict["auto_decline_enabled"] = auto_decline_enabled
        if condition_groups is not UNSET:
            field_dict["condition_groups"] = condition_groups
        if incident_template is not UNSET:
            field_dict["incident_template"] = incident_template
        if membership_teams is not UNSET:
            field_dict["membership_teams"] = membership_teams
        if template is not UNSET:
            field_dict["template"] = template

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        from ..models.alert_route_incident_template_payload_v3 import (
            AlertRouteIncidentTemplatePayloadV3,
        )
        from ..models.condition_group_payload_v3 import (
            ConditionGroupPayloadV3,
        )
        from ..models.engine_param_binding_payload_v3 import (
            EngineParamBindingPayloadV3,
        )

        d = dict(src_dict)
        enabled = d.pop("enabled")

        auto_decline_enabled = d.pop("auto_decline_enabled", UNSET)

        _condition_groups = d.pop("condition_groups", UNSET)
        condition_groups: list[ConditionGroupPayloadV3] | Unset = UNSET
        if _condition_groups is not UNSET:
            condition_groups = []
            for condition_groups_item_data in _condition_groups:
                condition_groups_item = ConditionGroupPayloadV3.from_dict(
                    condition_groups_item_data
                )

                condition_groups.append(condition_groups_item)

        _incident_template = d.pop("incident_template", UNSET)
        incident_template: EngineParamBindingPayloadV3 | Unset
        if isinstance(_incident_template, Unset):
            incident_template = UNSET
        else:
            incident_template = EngineParamBindingPayloadV3.from_dict(
                _incident_template
            )

        _membership_teams = d.pop("membership_teams", UNSET)
        membership_teams: EngineParamBindingPayloadV3 | Unset
        if isinstance(_membership_teams, Unset):
            membership_teams = UNSET
        else:
            membership_teams = EngineParamBindingPayloadV3.from_dict(_membership_teams)

        _template = d.pop("template", UNSET)
        template: AlertRouteIncidentTemplatePayloadV3 | Unset
        if isinstance(_template, Unset):
            template = UNSET
        else:
            template = AlertRouteIncidentTemplatePayloadV3.from_dict(_template)

        alert_route_incident_config_payload_v3 = cls(
            enabled=enabled,
            auto_decline_enabled=auto_decline_enabled,
            condition_groups=condition_groups,
            incident_template=incident_template,
            membership_teams=membership_teams,
            template=template,
        )

        alert_route_incident_config_payload_v3.additional_properties = d
        return alert_route_incident_config_payload_v3

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
