from enum import StrEnum


class IncidentActivityLogEntryV2Type(StrEnum):
    ACTIONS_SHARED_IN_CHANNEL = "actions_shared_in_channel"
    ACTION_CREATED = "action_created"
    ACTION_UPDATED = "action_updated"
    ALERT_ATTACHED_TO_INCIDENT = "alert_attached_to_incident"
    ALERT_GROUP_ATTACHED_TO_INCIDENT = "alert_group_attached_to_incident"
    ALERT_GROUP_DETACHED_FROM_INCIDENT = "alert_group_detached_from_incident"
    ATLASSIAN_STATUSPAGE_UPDATE = "atlassian_statuspage_update"
    CALL_URL_CHANGED = "call_url_changed"
    CUSTOM_FIELD_VALUE_UPDATE = "custom_field_value_update"
    ESCALATION_ACKNOWLEDGED = "escalation_acknowledged"
    ESCALATION_CREATED = "escalation_created"
    EXTERNAL_ISSUE_COMMENT_SYNCED = "external_issue_comment_synced"
    FOLLOW_UPS_SHARED_IN_CHANNEL = "follow_ups_shared_in_channel"
    FOLLOW_UP_CREATED = "follow_up_created"
    FOLLOW_UP_UPDATED = "follow_up_updated"
    HANDOVER = "handover"
    INCIDENT_ATTACHMENT_ADDED = "incident_attachment_added"
    INCIDENT_ATTACHMENT_REMOVED = "incident_attachment_removed"
    INCIDENT_CALL_CREATED = "incident_call_created"
    INCIDENT_CALL_ENDED = "incident_call_ended"
    INCIDENT_CALL_PARTICIPANTS_UPDATED = "incident_call_participants_updated"
    INCIDENT_CALL_RECALL_BOT_STATUS_CHANGED = "incident_call_recall_bot_status_changed"
    INCIDENT_CALL_STARTED = "incident_call_started"
    INCIDENT_CALL_TRANSCRIPT_CURRENT_TOPIC_GENERATED = (
        "incident_call_transcript_current_topic_generated"
    )
    INCIDENT_CALL_TRANSCRIPT_KEY_MOMENT_GENERATED = (
        "incident_call_transcript_key_moment_generated"
    )
    INCIDENT_CALL_TRANSCRIPT_MESSAGE = "incident_call_transcript_message"
    INCIDENT_CALL_TRANSCRIPT_SUMMARY_GENERATED = (
        "incident_call_transcript_summary_generated"
    )
    INCIDENT_CHANNEL_CREATED = "incident_channel_created"
    INCIDENT_CHANNEL_JOIN = "incident_channel_join"
    INCIDENT_CHANNEL_LEAVE = "incident_channel_leave"
    INCIDENT_ESCALATE = "incident_escalate"
    INCIDENT_MEMBERSHIP_REVOKED = "incident_membership_revoked"
    INCIDENT_MERGED = "incident_merged"
    INCIDENT_RENAME = "incident_rename"
    INCIDENT_TIMESTAMP_OCCURRED = "incident_timestamp_occurred"
    INCIDENT_TIMESTAMP_SET = "incident_timestamp_set"
    INCIDENT_TYPE_CHANGED = "incident_type_changed"
    INCIDENT_UPDATE = "incident_update"
    INCIDENT_VISIBILITY_CHANGED = "incident_visibility_changed"
    INVESTIGATION_HYPOTHESIS_UPDATE = "investigation_hypothesis_update"
    MICROSOFT_TEAMS_ANNOUNCEMENT_REPLY = "microsoft_teams_announcement_reply"
    MICROSOFT_TEAMS_IMAGE = "microsoft_teams_image"
    MICROSOFT_TEAMS_MESSAGE = "microsoft_teams_message"
    MICROSOFT_TEAMS_PINNED_CHANNEL_MESSAGE = "microsoft_teams_pinned_channel_message"
    PAGERDUTY_INCIDENT_ACKNOWLEDGED = "pagerduty_incident_acknowledged"
    PAGERDUTY_INCIDENT_RESOLVED = "pagerduty_incident_resolved"
    PAGERDUTY_INCIDENT_TRIGGERED = "pagerduty_incident_triggered"
    POSTMORTEM_CHANGED = "postmortem_changed"
    POSTMORTEM_DOCUMENT_V2_CHANGED = "postmortem_document_v2_changed"
    ROLE_UPDATE = "role_update"
    SCRIBE_ADDED = "scribe_added"
    SCRIBE_REMOVED = "scribe_removed"
    SCRUB = "scrub"
    SLACK_IMAGE = "slack_image"
    SLACK_INFER_SENTRY = "slack_infer_sentry"
    SLACK_MESSAGE = "slack_message"
    SLACK_PIN = "slack_pin"
    STATUS_CHANGE = "status_change"
    STATUS_PAGE_INCIDENT_LINKED = "status_page_incident_linked"
    STATUS_PAGE_INCIDENT_UPDATED = "status_page_incident_updated"
    SUMMARY_UPDATE = "summary_update"
    USER_INTENT_DECLARED = "user_intent_declared"
    WORKFLOW_RAN = "workflow_ran"

    def __str__(self) -> str:
        return str(self.value)
